name: Demo Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    name: Deploy to demo
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: htech/demo-image
      TASK_NAME: htech-demo-app-task
      CLUSTER_NAME: htech-demo-ecs-cluster
      SERVICE_NAME: htech-demo-app-service
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login_ecr

      - name: Build, tag, and push image to Amazon ECR
        id: build_image
        env:
          IMAGE_NAME: ${{ steps.login_ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
        run: |
          docker build --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME:${GITHUB_REF##*/} -t $IMAGE_NAME:latest -f Dockerfile .
          docker push $IMAGE_NAME:${GITHUB_REF##*/}
          docker push $IMAGE_NAME:latest
          echo "::set-output name=image::$IMAGE_NAME:${GITHUB_REF##*/}"
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.TASK_NAME }} --query taskDefinition > task-definition.json
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task_def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.TASK_NAME }}
          image: ${{ steps.build_image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task_def.outputs.task-definition }}
          service: ${{ env.SERVICE_NAME }}
          cluster: ${{ env.CLUSTER_NAME }}
          wait-for-service-stability: true